//TO DO: Build group dashboard pageimport Head from "next/head";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../../config/session";
import db from '../../db'
import Link from "next/link";
import Head from 'next/head';
import Header from "../../components/header";
import Footer from "../../components/footer";



export const getServerSideProps = withIronSessionSsr (
  async function getServerSideProps({ req, params}) {

    const props = {};

    //Get user session information
    const user = req.session.user;
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }

    const group = await db.group.getGroupById(params.groupId)
    const groupConverted = JSON.parse(JSON.stringify(group))


    if(group !== null){
        props.group = groupConverted
      }

    return { props };
  },
  sessionOptions
);


export default function GroupPage(props) {
  const router = useRouter();
  const menuType = "group"

  return (
    <div >
      <Head>
        <title>My Cookie Jar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} menu={menuType} groupId={props.group.id}/>

      <main >

        <div>
          <h1 >Group Member List</h1>
          <h3> Page In Progress</h3>
        </div>

       <div>
          <h1>Group Members</h1>
          {props.group.groupMembers ? (
            <>
              {props.group.groupMembers.map((member, i) => (
                <GroupMembers 
                  key={i}
                  groupId={props.group.id}
                  memberId={member._id}
                  userId={member.userId} 
                  memberName={member.memberName} 
                  memberRole={member.memberRole}
                  id={member._id}>
                </GroupMembers>
              ))}
            </>
            ):( 
              <>
              </>
          )}
        </div>
   
      </main>

      <Footer/>

    </div>      
   );         
}


function GroupMembers({userId, memberRole, groupId, memberName, memberId}) {

  return (
    <div>
      <Link href={`/member?g=${groupId}&m=${memberId}`}>
        <h3>Member Name: {memberName}</h3>
      </Link>
        

    </div>  
    
  )
}

