//TO DO: Build group dashboard pageimport Head from "next/head";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../../config/session";
import db from '../../db'
import Link from "next/link";
import Head from 'next/head';
import Header from "../../components/header";
import Footer from "../../components/footer";
import styles from "../../styles/members.module.css"


export const getServerSideProps = withIronSessionSsr (
  async function getServerSideProps({ req, params}) {

    const props = {};

    //Get user session information
    const user = req.session.user;
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }

    const group = await db.group.getGroupById(params.groupId)
    const groupConverted = JSON.parse(JSON.stringify(group))


    if(group !== null){
        props.group = groupConverted
      }

    return { props };
  },
  sessionOptions
);


export default function GroupPage(props) {
  const router = useRouter();
  const menuType = "group"
  const pageTitle = `${props.group.groupName}`

  return (
    <div >
      <Head>
        <title>My Cookie Jar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} menu={menuType} pageTitle={pageTitle} groupId={props.group.id}/>

      <main className={styles.main}>

        <div className={styles.mainContainer}>

          <div>
              <h1>Members</h1>
          </div>


          <div className={styles.membersList}>
            {props.group.groupMembers ? (
              <>
                {props.group.groupMembers.map((member, i) => (
                  <GroupMembers 
                    key={i}
                    groupId={props.group.id}
                    memberId={member._id}
                    userId={member.userId} 
                    memberFirstName={member.memberFirstName} 
                    memberLastName={member.memberLastName}
                    memberRole={member.memberRole}
                    id={member._id}>
                  </GroupMembers>
                ))}
              </>
              ):( 
                <>
                </>
            )}
          </div>

        </div>  

      </main>

      <Footer/>

    </div>      
   );         
}


function GroupMembers({memberFirstName, memberLastName, groupId, memberId}) {

  return (

      <Link href={`/member?g=${groupId}&m=${memberId}`}>
        <p className={styles.button}> {memberFirstName} {memberLastName}</p>
      </Link>
        

 
    
  )
}

