//TO DO: Build group dashboard pageimport Head from "next/head";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import db from '../db'
import Head from 'next/head';
import Header from "../components/header";
import Footer from "../components/footer";



export const getServerSideProps = withIronSessionSsr (
  async function getServerSideProps({ req, query }) {
    
    const props = {};

    //Get active user session information
    const user = req.session.user;
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }

    //GET Member/User Info
    const groupId = query.g
    const boothId = query.b

    console.log("boothId: ", boothId)

    props.groupId = groupId

    const booth = await db.booth.getBoothById(boothId)
    const boothDetails = JSON.parse(JSON.stringify(booth))

    console.log("booth details: ", booth)


    if(boothDetails !== null){
      props.booth = boothDetails
    }
    
    return { props };
  },
  sessionOptions
);




export default function MemberPage(props) {
  const router = useRouter();
  const menuType = "group"

  return (
    <div >
      <Head>
        <title>My Cookie Jar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} menu={menuType} groupId={props.groupId}/>

      <main >
        <div>
          <h1 >
            Booth Details Page
          </h1>
        </div>

        <div>
          <p> Location Name: {props.booth.locationName}</p>
          <p> Date/Time: {props.booth.date} @ {props.booth.time}{props.booth.amPM}</p>
          <p> # of Shifts Available: {props.booth.shifts}</p>
          <p> Address: {props.booth.address}, {props.booth.city}, {props.booth.state}</p>
          

          <iframe
            width="300"
            height="300"
            loading="lazy"
            allowfullscreen
            referrerpolicy="no-referrer-when-downgrade"
            src={`https://www.google.com/maps/embed/v1/place?key=${process.env.NEXT_PUBLIC_API_KEY}&q=${props.booth.address}+${props.booth.city}+${props.booth.state}`}>
          </iframe>

          <div>
            <p> Important Notes: {props.booth.notes}</p>
          </div>
          

        </div>

      </main>

      <Footer/>

    </div>      
   );         
}
