import Head from "next/head";
import Header from "../components/header";
import Footer from "../components/footer";
import { useRouter } from "next/router";
import { useState } from "react";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";


export const getServerSideProps = withIronSessionSsr (
    async function getServerSideProps({ req }) {
  
      const props = {}
  
      //Get user session information
      const user = req.session.user;
      if (user) {
        props.user = req.session.user;
        props.isLoggedIn = true;
      } else {
          return {
            redirect: {
              permanent: false,
              destination: "/",
            },
            props:{},
          };
      }
  
      return { props };
    },
    sessionOptions
);

export default function CreateGroup(props) {
    const router = useRouter();
    const menuType = "user"

    const [
      { groupName, groupCode, "confirm-code": confirmCode},
      setForm,
    ] = useState({
      groupName: "",
      groupCode: "",
      "confirm-code": "",
    });
    const [error, setError] = useState("");
  
    function handleChange(e) {
      setForm({
        groupName,
        groupCode,
        "confirm-code": confirmCode,
        ...{ [e.target.name]: e.target.value.trim() },
      });
    }
    async function handleCreateAccount(e) {
      e.preventDefault();
      if (!groupName) return setError("Must include group name");
      if (groupCode !== confirmCode) return setError("Passwords must Match");
  
      try {
        const res = await fetch("/api/group", {
          method: "POST",
          headers: {
            "content-type": "application/json",
          },
          body: JSON.stringify({ groupName, groupCode }),
        });
        if (res.status === 200) return router.push("/dashboard");
        const { error: message } = await res.json();
        setError(message);
      } catch (err) {
        console.log(err);
      }
    }





    return (
      <div >
        <Head>
          <title>Create A Group</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
  
        <Header isLoggedIn={props.isLoggedIn}  menu={menuType}/>
  
        <main>
          <h1>
            Create A Group!
          </h1>
  
  
          <form
            onSubmit={handleCreateAccount}
          >
            <label htmlFor="groupName">Group Name: </label>
            <input
              type="text"
              name="groupName"
              id="groupName"
              onChange={handleChange}
              value={groupName}
            />
  
            <label htmlFor="groupCode">Group Code: </label>
            <input
              type="text"
              name="groupCode"
              id="groupCode"
              onChange={handleChange}
              value={groupCode}
            />
  
            <label htmlFor="confirm-code">Confirm Group Code: </label>
            <input
              type="confirm-code"
              name="confirm-code"
              id="confirm-code"
              onChange={handleChange}
              value={confirmCode}
            />
  
            <button>Submit</button>
            {error && <p>{error}</p>}
          </form>
        </main>
  
        <Footer/>
      </div>
    );
  }