import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Footer from "../components/footer";
import styles from "../styles/Home.module.css";
import Image from 'next/image';


export default function Home(props) {
  const router = useRouter();

  return (
    <div >
      <Head>
        <title>My Cookie Jar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <div className={styles.main}>


          <div className={styles.mainContainer}>
            
          <Image alt="cookie jar logo" src="/cookieJarLogo.png" className={styles.logo} width="3000" height="1928"/>

                  <h1 className={styles.pageTitle}>
                    Welcome to My Cookie Jar
                  </h1>

                  
                  <div className = {styles.welcomeMessage}>
                    <p>Ready to conquer Cookie Season like a pro? </p>
                    <p>Sign in or register to manage booth schedules and inventory, track orders, and keep everything organized. </p>
                    <p>Let's make this the best season ever! </p>
                  </div>
              
              <div className={styles.button}>
                  <Link href="/login">
                    <p>Login </p>
                  </Link>
              </div>

              <div className={styles.button}>
                  <Link href="/signup">
                    <p>Sign Up </p>
                  </Link>
              </div>

          </div>
          

        </div>
      </main>

      <Footer/>
    </div>
  );
}

