import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Footer from "../components/footer";
import styles from "../styles/Home.module.css";
import Image from 'next/image';


export default function Home(props) {
  const router = useRouter();

  return (
    <div >
      <Head>
        <title>My Cookie Jar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <div className={styles.main}>


          <div className={styles.mainContainer}>
            
          <Image src="/cookieJarLogo.png" className={styles.logo} width="3000" height="1928"/>

                  <h1>
                    Welcome to My Cookie Jar
                  </h1>

                  
                  <h2>
                    Log in or Sign up!
                  </h2>
              
              <div className={styles.button}>
                  <Link href="/login">
                    <h2>Login </h2>
                  </Link>
              </div>

              <div className={styles.button}>
                  <Link href="/signup">
                    <h2>Sign Up </h2>
                  </Link>
              </div>

          </div>
          

        </div>
      </main>

      <Footer/>
    </div>
  );
}

