import Head from "next/head";
import Header from "../components/header";
import Footer from "../components/footer";
import { useRouter } from "next/router";
import { useState } from "react";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";

export const getServerSideProps = withIronSessionSsr (
    async function getServerSideProps({ req }) {
  
      const props = {}
  
      //Get user session information
      const user = req.session.user;
      if (user) {
        props.user = req.session.user;
        props.isLoggedIn = true;
      } else {
          return {
            redirect: {
              permanent: false,
              destination: "/",
            },
            props:{},
          };
      }
  
      return { props };
    },
    sessionOptions
);

export default function JoinGroup(props) {
    const router = useRouter();
    const menuType = "user"
    const [
      { groupName, groupCode},
      setForm,
    ] = useState({
      groupName: "",
      groupCode: "",
    });
    const [error, setError] = useState("");
  
    function handleChange(e) {
      setForm({
        groupName,
        groupCode,
        ...{ [e.target.name]: e.target.value.trim() },
      });
    }
    async function handleCreateAccount(e) {
      e.preventDefault();
      if (!groupName) return setError("Must include group name");
      if (!groupCode) return setError("Must include group code");
  
      try {
        const res = await fetch("/api/user", {
          method: "POST",
          headers: {
            "content-type": "application/json",
          },
          body: JSON.stringify({ groupName, groupCode }),
        });
        if (res.status === 200) return router.push("/dashboard");
        const { error: message } = await res.json();
        setError(message);
      } catch (err) {
        console.log(err);
      }
    }





    return (
      <div >
        <Head>
          <title>Join A Group</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
  
        <Header isLoggedIn={props.isLoggedIn} menu={menuType}/>
  
        <main>
          <h1>
            Search A Group To Join!
          </h1>
  
  
          <form
            onSubmit={handleCreateAccount}
          >
            <label htmlFor="groupName">Group Name: </label>
            <input
              type="text"
              name="groupName"
              id="groupName"
              onChange={handleChange}
              value={groupName}
            />
  
            <label htmlFor="groupCode">Group Code: </label>
            <input
              type="text"
              name="groupCode"
              id="groupCode"
              onChange={handleChange}
              value={groupCode}
            />
  
            <button>Submit</button>
            <button>
              <div>
                <Link href="/dashboard">Cancel</Link>
              </div> 
            </button>
            {error && <p>{error}</p>}
          </form>
        </main>
  
        <Footer/>
      </div>
    );
  }