import Head from "next/head";
import Header from "../components/header";
import Footer from "../components/footer";
import Link from "next/link";


export default function Login(props) {
  
  return (
    <div>
      <Head>
        <title>Log In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />

      <main>
        <h1>
          LogIn Page
        </h1>
        <Link href="/signup">
          <p>Signup instead?</p>
        </Link>

    
      </main>

      <Footer/>
    </div>
  );
}
