import Head from "next/head";
import Header from "../components/header";
import Footer from "../components/footer";
import { useRouter } from "next/router";
import { useState } from "react";
import Link from "next/link";


export default function Signup(props) {
  const router = useRouter();
  const [
    { username, password, "confirm-password": confirmPassword, fullName, email},
    setForm,
  ] = useState({
    username: "",
    password: "",
    "confirm-password": "",
    fullName:"",
    email: "",
  });
  const [error, setError] = useState("");

  function handleChange(e) {
    setForm({
      username,
      password,
      "confirm-password": confirmPassword,
      fullName,
      email,
      ...{ [e.target.name]: e.target.value.trim() },
    });
  }
  async function handleCreateAccount(e) {
    e.preventDefault();
    if (!username) return setError("Must include username");
    if (password !== confirmPassword) return setError("Passwords must Match");
    if (!fullName) return setError("Must include your first and last name");
    if (!email) return setError("Must include your email");

    try {
      const res = await fetch("/api/auth/signup", {
        method: "POST",
        headers: {
          "content-type": "application/json",
        },
        body: JSON.stringify({ username, password, fullName, email }),
      });
      if (res.status === 200) return router.push("/dashboard");
      const { error: message } = await res.json();
      setError(message);
    } catch (err) {
      console.log(err);
    }
  }
  return (
    <div >
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />

      <main>
        <h1>
          Create an Account!
        </h1>


        <form
          onSubmit={handleCreateAccount}
        >
          <label htmlFor="fullName">First and Last Name: </label>
          <input
            type="text"
            name="fullName"
            id="fullName"
            onChange={handleChange}
            value={fullName}
          />

          <label htmlFor="email">Email: </label>
          <input
            type="text"
            name="email"
            id="email"
            onChange={handleChange}
            value={email}
          />

          <label htmlFor="username">Username: </label>
          <input
            type="text"
            name="username"
            id="username"
            onChange={handleChange}
            value={username}
          />

          <label htmlFor="password">Password: </label>
          <input
            type="password"
            name="password"
            id="password"
            onChange={handleChange}
            value={password}
          />

          <label htmlFor="confirm-password">Confirm Password: </label>
          <input
            type="password"
            name="confirm-password"
            id="confirm-password"
            onChange={handleChange}
            value={confirmPassword}
          />

          <button>Submit</button>
          {error && <p>{error}</p>}
        </form>
        <Link href="/login">
          <p>Login instead?</p>
        </Link>
      </main>

      <Footer/>
    </div>
  );
}
