//TO DO: Build group dashboard pageimport Head from "next/head";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../../config/session";
import db from '../../db'
import Link from "next/link";
import Head from 'next/head';
import Header from "../../components/header";
import Footer from "../../components/footer";


export const getServerSideProps = withIronSessionSsr (
  async function getServerSideProps({ req, params }) {

    const props = {};

    //Get user session information
    const user = req.session.user;
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }

    //TO DO: Get user groups 
    // const group = await db.group.getGroupById(user._id, params.id)
    const group = await db.group.getGroupById(params.id)

    const groupConverted = JSON.parse(JSON.stringify(group))

    let member = {}

    for( let i = 0; i < groupConverted.groupMembers.length; i++){
      if (groupConverted.groupMembers[i].userId === user._id){
        member = groupConverted.groupMembers[i]
      }
    }

    console.log ("member: ", member)

    //TO DO: Parsing turns it to Javascript to read in browser




    if(group !== null){
        props.group = groupConverted
      }
      
    return { props };
  },
  sessionOptions
);




export default function MemberPage(props) {
  const router = useRouter();
  const menuType = "group"

  return (
    <div >
      <Head>
        <title>My Cookie Jar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} menu={menuType} groupId={props.group.id}/>

      <main >
        <div>
          <h1 >
            Member Page
          </h1>
        </div>

        <div>
          <p> User ID: {props.user._id}</p>
          <p> Member Name:{props.user.name}</p>
          <p> Member Email: {props.user.email}</p>
          <p> Member Role: {props.group.groupCode}</p>
        </div>

        


      </main>

      <Footer/>

    </div>      
   );         
}
